name = "pokebase-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_URL = "https://api.pokemon.solclarus.me"
IMAGES_BASE_URL = "https://images.pokemon.solclarus.me"
