name = "pokemon-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_API_URL = "https://api.pokemon.solclarus.me"
API_URL = "https://api.pokemon.solclarus.me"
