import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const DATA_DIR = join(import.meta.dirname, "../data");

type Pokemon = {
  id: number;
  identifier: string;
  name: { ja: string; en: string };
  is_legendary: boolean;
  is_mythical: boolean;
  forms: Array<{
    form_id: string;
    identifier: string;
    name: { ja: string; en: string };
    form_type: string;
    types: string[];
    stats: { hp: number; attack: number; defense: number; sp_attack: number; sp_defense: number; speed: number };
    ability_ids: number[];
    hidden_ability_id?: number;
  }>;
};

const gen1Pokemon: Pokemon[] = [
  { id: 1, identifier: "bulbasaur", name: { ja: "フシギダネ", en: "Bulbasaur" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0001-default", identifier: "bulbasaur", name: { ja: "フシギダネ", en: "Bulbasaur" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 45, attack: 49, defense: 49, sp_attack: 65, sp_defense: 65, speed: 45 }, ability_ids: [65], hidden_ability_id: 34 }] },
  { id: 2, identifier: "ivysaur", name: { ja: "フシギソウ", en: "Ivysaur" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0002-default", identifier: "ivysaur", name: { ja: "フシギソウ", en: "Ivysaur" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 60, attack: 62, defense: 63, sp_attack: 80, sp_defense: 80, speed: 60 }, ability_ids: [65], hidden_ability_id: 34 }] },
  { id: 3, identifier: "venusaur", name: { ja: "フシギバナ", en: "Venusaur" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0003-default", identifier: "venusaur", name: { ja: "フシギバナ", en: "Venusaur" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 80, attack: 82, defense: 83, sp_attack: 100, sp_defense: 100, speed: 80 }, ability_ids: [65], hidden_ability_id: 34 }, { form_id: "0003-mega", identifier: "venusaur-mega", name: { ja: "メガフシギバナ", en: "Mega Venusaur" }, form_type: "mega", types: ["grass", "poison"], stats: { hp: 80, attack: 100, defense: 123, sp_attack: 122, sp_defense: 120, speed: 80 }, ability_ids: [47] }] },
  { id: 4, identifier: "charmander", name: { ja: "ヒトカゲ", en: "Charmander" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0004-default", identifier: "charmander", name: { ja: "ヒトカゲ", en: "Charmander" }, form_type: "default", types: ["fire"], stats: { hp: 39, attack: 52, defense: 43, sp_attack: 60, sp_defense: 50, speed: 65 }, ability_ids: [66], hidden_ability_id: 94 }] },
  { id: 5, identifier: "charmeleon", name: { ja: "リザード", en: "Charmeleon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0005-default", identifier: "charmeleon", name: { ja: "リザード", en: "Charmeleon" }, form_type: "default", types: ["fire"], stats: { hp: 58, attack: 64, defense: 58, sp_attack: 80, sp_defense: 65, speed: 80 }, ability_ids: [66], hidden_ability_id: 94 }] },
  { id: 6, identifier: "charizard", name: { ja: "リザードン", en: "Charizard" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0006-default", identifier: "charizard", name: { ja: "リザードン", en: "Charizard" }, form_type: "default", types: ["fire", "flying"], stats: { hp: 78, attack: 84, defense: 78, sp_attack: 109, sp_defense: 85, speed: 100 }, ability_ids: [66], hidden_ability_id: 94 }, { form_id: "0006-mega-x", identifier: "charizard-mega-x", name: { ja: "メガリザードンX", en: "Mega Charizard X" }, form_type: "mega", types: ["fire", "dragon"], stats: { hp: 78, attack: 130, defense: 111, sp_attack: 130, sp_defense: 85, speed: 100 }, ability_ids: [153] }, { form_id: "0006-mega-y", identifier: "charizard-mega-y", name: { ja: "メガリザードンY", en: "Mega Charizard Y" }, form_type: "mega", types: ["fire", "flying"], stats: { hp: 78, attack: 104, defense: 78, sp_attack: 159, sp_defense: 115, speed: 100 }, ability_ids: [70] }] },
  { id: 7, identifier: "squirtle", name: { ja: "ゼニガメ", en: "Squirtle" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0007-default", identifier: "squirtle", name: { ja: "ゼニガメ", en: "Squirtle" }, form_type: "default", types: ["water"], stats: { hp: 44, attack: 48, defense: 65, sp_attack: 50, sp_defense: 64, speed: 43 }, ability_ids: [67], hidden_ability_id: 44 }] },
  { id: 8, identifier: "wartortle", name: { ja: "カメール", en: "Wartortle" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0008-default", identifier: "wartortle", name: { ja: "カメール", en: "Wartortle" }, form_type: "default", types: ["water"], stats: { hp: 59, attack: 63, defense: 80, sp_attack: 65, sp_defense: 80, speed: 58 }, ability_ids: [67], hidden_ability_id: 44 }] },
  { id: 9, identifier: "blastoise", name: { ja: "カメックス", en: "Blastoise" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0009-default", identifier: "blastoise", name: { ja: "カメックス", en: "Blastoise" }, form_type: "default", types: ["water"], stats: { hp: 79, attack: 83, defense: 100, sp_attack: 85, sp_defense: 105, speed: 78 }, ability_ids: [67], hidden_ability_id: 44 }, { form_id: "0009-mega", identifier: "blastoise-mega", name: { ja: "メガカメックス", en: "Mega Blastoise" }, form_type: "mega", types: ["water"], stats: { hp: 79, attack: 103, defense: 120, sp_attack: 135, sp_defense: 115, speed: 78 }, ability_ids: [178] }] },
  { id: 10, identifier: "caterpie", name: { ja: "キャタピー", en: "Caterpie" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0010-default", identifier: "caterpie", name: { ja: "キャタピー", en: "Caterpie" }, form_type: "default", types: ["bug"], stats: { hp: 45, attack: 30, defense: 35, sp_attack: 20, sp_defense: 20, speed: 45 }, ability_ids: [19], hidden_ability_id: 50 }] },
  { id: 11, identifier: "metapod", name: { ja: "トランセル", en: "Metapod" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0011-default", identifier: "metapod", name: { ja: "トランセル", en: "Metapod" }, form_type: "default", types: ["bug"], stats: { hp: 50, attack: 20, defense: 55, sp_attack: 25, sp_defense: 25, speed: 30 }, ability_ids: [61] }] },
  { id: 12, identifier: "butterfree", name: { ja: "バタフリー", en: "Butterfree" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0012-default", identifier: "butterfree", name: { ja: "バタフリー", en: "Butterfree" }, form_type: "default", types: ["bug", "flying"], stats: { hp: 60, attack: 45, defense: 50, sp_attack: 90, sp_defense: 80, speed: 70 }, ability_ids: [14], hidden_ability_id: 110 }] },
  { id: 13, identifier: "weedle", name: { ja: "ビードル", en: "Weedle" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0013-default", identifier: "weedle", name: { ja: "ビードル", en: "Weedle" }, form_type: "default", types: ["bug", "poison"], stats: { hp: 40, attack: 35, defense: 30, sp_attack: 20, sp_defense: 20, speed: 50 }, ability_ids: [19], hidden_ability_id: 50 }] },
  { id: 14, identifier: "kakuna", name: { ja: "コクーン", en: "Kakuna" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0014-default", identifier: "kakuna", name: { ja: "コクーン", en: "Kakuna" }, form_type: "default", types: ["bug", "poison"], stats: { hp: 45, attack: 25, defense: 50, sp_attack: 25, sp_defense: 25, speed: 35 }, ability_ids: [61] }] },
  { id: 15, identifier: "beedrill", name: { ja: "スピアー", en: "Beedrill" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0015-default", identifier: "beedrill", name: { ja: "スピアー", en: "Beedrill" }, form_type: "default", types: ["bug", "poison"], stats: { hp: 65, attack: 90, defense: 40, sp_attack: 45, sp_defense: 80, speed: 75 }, ability_ids: [68], hidden_ability_id: 97 }, { form_id: "0015-mega", identifier: "beedrill-mega", name: { ja: "メガスピアー", en: "Mega Beedrill" }, form_type: "mega", types: ["bug", "poison"], stats: { hp: 65, attack: 150, defense: 40, sp_attack: 15, sp_defense: 80, speed: 145 }, ability_ids: [91] }] },
  { id: 16, identifier: "pidgey", name: { ja: "ポッポ", en: "Pidgey" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0016-default", identifier: "pidgey", name: { ja: "ポッポ", en: "Pidgey" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 40, attack: 45, defense: 40, sp_attack: 35, sp_defense: 35, speed: 56 }, ability_ids: [51, 77], hidden_ability_id: 145 }] },
  { id: 17, identifier: "pidgeotto", name: { ja: "ピジョン", en: "Pidgeotto" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0017-default", identifier: "pidgeotto", name: { ja: "ピジョン", en: "Pidgeotto" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 63, attack: 60, defense: 55, sp_attack: 50, sp_defense: 50, speed: 71 }, ability_ids: [51, 77], hidden_ability_id: 145 }] },
  { id: 18, identifier: "pidgeot", name: { ja: "ピジョット", en: "Pidgeot" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0018-default", identifier: "pidgeot", name: { ja: "ピジョット", en: "Pidgeot" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 83, attack: 80, defense: 75, sp_attack: 70, sp_defense: 70, speed: 101 }, ability_ids: [51, 77], hidden_ability_id: 145 }, { form_id: "0018-mega", identifier: "pidgeot-mega", name: { ja: "メガピジョット", en: "Mega Pidgeot" }, form_type: "mega", types: ["normal", "flying"], stats: { hp: 83, attack: 80, defense: 80, sp_attack: 135, sp_defense: 80, speed: 121 }, ability_ids: [171] }] },
  { id: 19, identifier: "rattata", name: { ja: "コラッタ", en: "Rattata" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0019-default", identifier: "rattata", name: { ja: "コラッタ", en: "Rattata" }, form_type: "default", types: ["normal"], stats: { hp: 30, attack: 56, defense: 35, sp_attack: 25, sp_defense: 35, speed: 72 }, ability_ids: [50, 62], hidden_ability_id: 55 }] },
  { id: 20, identifier: "raticate", name: { ja: "ラッタ", en: "Raticate" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0020-default", identifier: "raticate", name: { ja: "ラッタ", en: "Raticate" }, form_type: "default", types: ["normal"], stats: { hp: 55, attack: 81, defense: 60, sp_attack: 50, sp_defense: 70, speed: 97 }, ability_ids: [50, 62], hidden_ability_id: 55 }] },
  { id: 21, identifier: "spearow", name: { ja: "オニスズメ", en: "Spearow" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0021-default", identifier: "spearow", name: { ja: "オニスズメ", en: "Spearow" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 40, attack: 60, defense: 30, sp_attack: 31, sp_defense: 31, speed: 70 }, ability_ids: [51], hidden_ability_id: 97 }] },
  { id: 22, identifier: "fearow", name: { ja: "オニドリル", en: "Fearow" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0022-default", identifier: "fearow", name: { ja: "オニドリル", en: "Fearow" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 65, attack: 90, defense: 65, sp_attack: 61, sp_defense: 61, speed: 100 }, ability_ids: [51], hidden_ability_id: 97 }] },
  { id: 23, identifier: "ekans", name: { ja: "アーボ", en: "Ekans" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0023-default", identifier: "ekans", name: { ja: "アーボ", en: "Ekans" }, form_type: "default", types: ["poison"], stats: { hp: 35, attack: 60, defense: 44, sp_attack: 40, sp_defense: 54, speed: 55 }, ability_ids: [22, 61], hidden_ability_id: 127 }] },
  { id: 24, identifier: "arbok", name: { ja: "アーボック", en: "Arbok" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0024-default", identifier: "arbok", name: { ja: "アーボック", en: "Arbok" }, form_type: "default", types: ["poison"], stats: { hp: 60, attack: 95, defense: 69, sp_attack: 65, sp_defense: 79, speed: 80 }, ability_ids: [22, 61], hidden_ability_id: 127 }] },
  { id: 25, identifier: "pikachu", name: { ja: "ピカチュウ", en: "Pikachu" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0025-default", identifier: "pikachu", name: { ja: "ピカチュウ", en: "Pikachu" }, form_type: "default", types: ["electric"], stats: { hp: 35, attack: 55, defense: 40, sp_attack: 50, sp_defense: 50, speed: 90 }, ability_ids: [9], hidden_ability_id: 31 }] },
  { id: 26, identifier: "raichu", name: { ja: "ライチュウ", en: "Raichu" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0026-default", identifier: "raichu", name: { ja: "ライチュウ", en: "Raichu" }, form_type: "default", types: ["electric"], stats: { hp: 60, attack: 90, defense: 55, sp_attack: 90, sp_defense: 80, speed: 110 }, ability_ids: [9], hidden_ability_id: 31 }] },
  { id: 27, identifier: "sandshrew", name: { ja: "サンド", en: "Sandshrew" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0027-default", identifier: "sandshrew", name: { ja: "サンド", en: "Sandshrew" }, form_type: "default", types: ["ground"], stats: { hp: 50, attack: 75, defense: 85, sp_attack: 20, sp_defense: 30, speed: 40 }, ability_ids: [8], hidden_ability_id: 146 }] },
  { id: 28, identifier: "sandslash", name: { ja: "サンドパン", en: "Sandslash" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0028-default", identifier: "sandslash", name: { ja: "サンドパン", en: "Sandslash" }, form_type: "default", types: ["ground"], stats: { hp: 75, attack: 100, defense: 110, sp_attack: 45, sp_defense: 55, speed: 65 }, ability_ids: [8], hidden_ability_id: 146 }] },
  { id: 29, identifier: "nidoran-f", name: { ja: "ニドラン♀", en: "Nidoran♀" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0029-default", identifier: "nidoran-f", name: { ja: "ニドラン♀", en: "Nidoran♀" }, form_type: "default", types: ["poison"], stats: { hp: 55, attack: 47, defense: 52, sp_attack: 40, sp_defense: 40, speed: 41 }, ability_ids: [38, 79], hidden_ability_id: 55 }] },
  { id: 30, identifier: "nidorina", name: { ja: "ニドリーナ", en: "Nidorina" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0030-default", identifier: "nidorina", name: { ja: "ニドリーナ", en: "Nidorina" }, form_type: "default", types: ["poison"], stats: { hp: 70, attack: 62, defense: 67, sp_attack: 55, sp_defense: 55, speed: 56 }, ability_ids: [38, 79], hidden_ability_id: 55 }] },
  { id: 31, identifier: "nidoqueen", name: { ja: "ニドクイン", en: "Nidoqueen" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0031-default", identifier: "nidoqueen", name: { ja: "ニドクイン", en: "Nidoqueen" }, form_type: "default", types: ["poison", "ground"], stats: { hp: 90, attack: 92, defense: 87, sp_attack: 75, sp_defense: 85, speed: 76 }, ability_ids: [38, 79], hidden_ability_id: 125 }] },
  { id: 32, identifier: "nidoran-m", name: { ja: "ニドラン♂", en: "Nidoran♂" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0032-default", identifier: "nidoran-m", name: { ja: "ニドラン♂", en: "Nidoran♂" }, form_type: "default", types: ["poison"], stats: { hp: 46, attack: 57, defense: 40, sp_attack: 40, sp_defense: 40, speed: 50 }, ability_ids: [38, 79], hidden_ability_id: 55 }] },
  { id: 33, identifier: "nidorino", name: { ja: "ニドリーノ", en: "Nidorino" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0033-default", identifier: "nidorino", name: { ja: "ニドリーノ", en: "Nidorino" }, form_type: "default", types: ["poison"], stats: { hp: 61, attack: 72, defense: 57, sp_attack: 55, sp_defense: 55, speed: 65 }, ability_ids: [38, 79], hidden_ability_id: 55 }] },
  { id: 34, identifier: "nidoking", name: { ja: "ニドキング", en: "Nidoking" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0034-default", identifier: "nidoking", name: { ja: "ニドキング", en: "Nidoking" }, form_type: "default", types: ["poison", "ground"], stats: { hp: 81, attack: 102, defense: 77, sp_attack: 85, sp_defense: 75, speed: 85 }, ability_ids: [38, 79], hidden_ability_id: 125 }] },
  { id: 35, identifier: "clefairy", name: { ja: "ピッピ", en: "Clefairy" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0035-default", identifier: "clefairy", name: { ja: "ピッピ", en: "Clefairy" }, form_type: "default", types: ["fairy"], stats: { hp: 70, attack: 45, defense: 48, sp_attack: 60, sp_defense: 65, speed: 35 }, ability_ids: [56, 98], hidden_ability_id: 132 }] },
  { id: 36, identifier: "clefable", name: { ja: "ピクシー", en: "Clefable" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0036-default", identifier: "clefable", name: { ja: "ピクシー", en: "Clefable" }, form_type: "default", types: ["fairy"], stats: { hp: 95, attack: 70, defense: 73, sp_attack: 95, sp_defense: 90, speed: 60 }, ability_ids: [56, 98], hidden_ability_id: 109 }] },
  { id: 37, identifier: "vulpix", name: { ja: "ロコン", en: "Vulpix" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0037-default", identifier: "vulpix", name: { ja: "ロコン", en: "Vulpix" }, form_type: "default", types: ["fire"], stats: { hp: 38, attack: 41, defense: 40, sp_attack: 50, sp_defense: 65, speed: 65 }, ability_ids: [18], hidden_ability_id: 70 }] },
  { id: 38, identifier: "ninetales", name: { ja: "キュウコン", en: "Ninetales" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0038-default", identifier: "ninetales", name: { ja: "キュウコン", en: "Ninetales" }, form_type: "default", types: ["fire"], stats: { hp: 73, attack: 76, defense: 75, sp_attack: 81, sp_defense: 100, speed: 100 }, ability_ids: [18], hidden_ability_id: 70 }] },
  { id: 39, identifier: "jigglypuff", name: { ja: "プリン", en: "Jigglypuff" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0039-default", identifier: "jigglypuff", name: { ja: "プリン", en: "Jigglypuff" }, form_type: "default", types: ["normal", "fairy"], stats: { hp: 115, attack: 45, defense: 20, sp_attack: 45, sp_defense: 25, speed: 20 }, ability_ids: [56, 172], hidden_ability_id: 132 }] },
  { id: 40, identifier: "wigglytuff", name: { ja: "プクリン", en: "Wigglytuff" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0040-default", identifier: "wigglytuff", name: { ja: "プクリン", en: "Wigglytuff" }, form_type: "default", types: ["normal", "fairy"], stats: { hp: 140, attack: 70, defense: 45, sp_attack: 85, sp_defense: 50, speed: 45 }, ability_ids: [56, 172], hidden_ability_id: 119 }] },
  { id: 41, identifier: "zubat", name: { ja: "ズバット", en: "Zubat" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0041-default", identifier: "zubat", name: { ja: "ズバット", en: "Zubat" }, form_type: "default", types: ["poison", "flying"], stats: { hp: 40, attack: 45, defense: 35, sp_attack: 30, sp_defense: 40, speed: 55 }, ability_ids: [39], hidden_ability_id: 151 }] },
  { id: 42, identifier: "golbat", name: { ja: "ゴルバット", en: "Golbat" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0042-default", identifier: "golbat", name: { ja: "ゴルバット", en: "Golbat" }, form_type: "default", types: ["poison", "flying"], stats: { hp: 75, attack: 80, defense: 70, sp_attack: 65, sp_defense: 75, speed: 90 }, ability_ids: [39], hidden_ability_id: 151 }] },
  { id: 43, identifier: "oddish", name: { ja: "ナゾノクサ", en: "Oddish" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0043-default", identifier: "oddish", name: { ja: "ナゾノクサ", en: "Oddish" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 45, attack: 50, defense: 55, sp_attack: 75, sp_defense: 65, speed: 30 }, ability_ids: [34], hidden_ability_id: 50 }] },
  { id: 44, identifier: "gloom", name: { ja: "クサイハナ", en: "Gloom" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0044-default", identifier: "gloom", name: { ja: "クサイハナ", en: "Gloom" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 60, attack: 65, defense: 70, sp_attack: 85, sp_defense: 75, speed: 40 }, ability_ids: [34], hidden_ability_id: 1 }] },
  { id: 45, identifier: "vileplume", name: { ja: "ラフレシア", en: "Vileplume" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0045-default", identifier: "vileplume", name: { ja: "ラフレシア", en: "Vileplume" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 75, attack: 80, defense: 85, sp_attack: 110, sp_defense: 90, speed: 50 }, ability_ids: [34], hidden_ability_id: 27 }] },
  { id: 46, identifier: "paras", name: { ja: "パラス", en: "Paras" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0046-default", identifier: "paras", name: { ja: "パラス", en: "Paras" }, form_type: "default", types: ["bug", "grass"], stats: { hp: 35, attack: 70, defense: 55, sp_attack: 45, sp_defense: 55, speed: 25 }, ability_ids: [27, 87], hidden_ability_id: 6 }] },
  { id: 47, identifier: "parasect", name: { ja: "パラセクト", en: "Parasect" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0047-default", identifier: "parasect", name: { ja: "パラセクト", en: "Parasect" }, form_type: "default", types: ["bug", "grass"], stats: { hp: 60, attack: 95, defense: 80, sp_attack: 60, sp_defense: 80, speed: 30 }, ability_ids: [27, 87], hidden_ability_id: 6 }] },
  { id: 48, identifier: "venonat", name: { ja: "コンパン", en: "Venonat" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0048-default", identifier: "venonat", name: { ja: "コンパン", en: "Venonat" }, form_type: "default", types: ["bug", "poison"], stats: { hp: 60, attack: 55, defense: 50, sp_attack: 40, sp_defense: 55, speed: 45 }, ability_ids: [14, 110], hidden_ability_id: 50 }] },
  { id: 49, identifier: "venomoth", name: { ja: "モルフォン", en: "Venomoth" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0049-default", identifier: "venomoth", name: { ja: "モルフォン", en: "Venomoth" }, form_type: "default", types: ["bug", "poison"], stats: { hp: 70, attack: 65, defense: 60, sp_attack: 90, sp_defense: 75, speed: 90 }, ability_ids: [19, 110], hidden_ability_id: 147 }] },
  { id: 50, identifier: "diglett", name: { ja: "ディグダ", en: "Diglett" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0050-default", identifier: "diglett", name: { ja: "ディグダ", en: "Diglett" }, form_type: "default", types: ["ground"], stats: { hp: 10, attack: 55, defense: 25, sp_attack: 35, sp_defense: 45, speed: 95 }, ability_ids: [8, 71], hidden_ability_id: 159 }] },
  { id: 51, identifier: "dugtrio", name: { ja: "ダグトリオ", en: "Dugtrio" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0051-default", identifier: "dugtrio", name: { ja: "ダグトリオ", en: "Dugtrio" }, form_type: "default", types: ["ground"], stats: { hp: 35, attack: 100, defense: 50, sp_attack: 50, sp_defense: 70, speed: 120 }, ability_ids: [8, 71], hidden_ability_id: 159 }] },
  { id: 52, identifier: "meowth", name: { ja: "ニャース", en: "Meowth" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0052-default", identifier: "meowth", name: { ja: "ニャース", en: "Meowth" }, form_type: "default", types: ["normal"], stats: { hp: 40, attack: 45, defense: 35, sp_attack: 40, sp_defense: 40, speed: 90 }, ability_ids: [53, 101], hidden_ability_id: 127 }] },
  { id: 53, identifier: "persian", name: { ja: "ペルシアン", en: "Persian" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0053-default", identifier: "persian", name: { ja: "ペルシアン", en: "Persian" }, form_type: "default", types: ["normal"], stats: { hp: 65, attack: 70, defense: 60, sp_attack: 65, sp_defense: 65, speed: 115 }, ability_ids: [7, 101], hidden_ability_id: 127 }] },
  { id: 54, identifier: "psyduck", name: { ja: "コダック", en: "Psyduck" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0054-default", identifier: "psyduck", name: { ja: "コダック", en: "Psyduck" }, form_type: "default", types: ["water"], stats: { hp: 50, attack: 52, defense: 48, sp_attack: 65, sp_defense: 50, speed: 55 }, ability_ids: [6, 13], hidden_ability_id: 33 }] },
  { id: 55, identifier: "golduck", name: { ja: "ゴルダック", en: "Golduck" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0055-default", identifier: "golduck", name: { ja: "ゴルダック", en: "Golduck" }, form_type: "default", types: ["water"], stats: { hp: 80, attack: 82, defense: 78, sp_attack: 95, sp_defense: 80, speed: 85 }, ability_ids: [6, 13], hidden_ability_id: 33 }] },
  { id: 56, identifier: "mankey", name: { ja: "マンキー", en: "Mankey" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0056-default", identifier: "mankey", name: { ja: "マンキー", en: "Mankey" }, form_type: "default", types: ["fighting"], stats: { hp: 40, attack: 80, defense: 35, sp_attack: 35, sp_defense: 45, speed: 70 }, ability_ids: [72, 83], hidden_ability_id: 128 }] },
  { id: 57, identifier: "primeape", name: { ja: "オコリザル", en: "Primeape" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0057-default", identifier: "primeape", name: { ja: "オコリザル", en: "Primeape" }, form_type: "default", types: ["fighting"], stats: { hp: 65, attack: 105, defense: 60, sp_attack: 60, sp_defense: 70, speed: 95 }, ability_ids: [72, 83], hidden_ability_id: 128 }] },
  { id: 58, identifier: "growlithe", name: { ja: "ガーディ", en: "Growlithe" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0058-default", identifier: "growlithe", name: { ja: "ガーディ", en: "Growlithe" }, form_type: "default", types: ["fire"], stats: { hp: 55, attack: 70, defense: 45, sp_attack: 70, sp_defense: 50, speed: 60 }, ability_ids: [22, 18], hidden_ability_id: 154 }] },
  { id: 59, identifier: "arcanine", name: { ja: "ウインディ", en: "Arcanine" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0059-default", identifier: "arcanine", name: { ja: "ウインディ", en: "Arcanine" }, form_type: "default", types: ["fire"], stats: { hp: 90, attack: 110, defense: 80, sp_attack: 100, sp_defense: 80, speed: 95 }, ability_ids: [22, 18], hidden_ability_id: 154 }] },
  { id: 60, identifier: "poliwag", name: { ja: "ニョロモ", en: "Poliwag" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0060-default", identifier: "poliwag", name: { ja: "ニョロモ", en: "Poliwag" }, form_type: "default", types: ["water"], stats: { hp: 40, attack: 50, defense: 40, sp_attack: 40, sp_defense: 40, speed: 90 }, ability_ids: [11, 6], hidden_ability_id: 33 }] },
  { id: 61, identifier: "poliwhirl", name: { ja: "ニョロゾ", en: "Poliwhirl" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0061-default", identifier: "poliwhirl", name: { ja: "ニョロゾ", en: "Poliwhirl" }, form_type: "default", types: ["water"], stats: { hp: 65, attack: 65, defense: 65, sp_attack: 50, sp_defense: 50, speed: 90 }, ability_ids: [11, 6], hidden_ability_id: 33 }] },
  { id: 62, identifier: "poliwrath", name: { ja: "ニョロボン", en: "Poliwrath" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0062-default", identifier: "poliwrath", name: { ja: "ニョロボン", en: "Poliwrath" }, form_type: "default", types: ["water", "fighting"], stats: { hp: 90, attack: 95, defense: 95, sp_attack: 70, sp_defense: 90, speed: 70 }, ability_ids: [11, 6], hidden_ability_id: 33 }] },
  { id: 63, identifier: "abra", name: { ja: "ケーシィ", en: "Abra" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0063-default", identifier: "abra", name: { ja: "ケーシィ", en: "Abra" }, form_type: "default", types: ["psychic"], stats: { hp: 25, attack: 20, defense: 15, sp_attack: 105, sp_defense: 55, speed: 90 }, ability_ids: [28, 39], hidden_ability_id: 98 }] },
  { id: 64, identifier: "kadabra", name: { ja: "ユンゲラー", en: "Kadabra" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0064-default", identifier: "kadabra", name: { ja: "ユンゲラー", en: "Kadabra" }, form_type: "default", types: ["psychic"], stats: { hp: 40, attack: 35, defense: 30, sp_attack: 120, sp_defense: 70, speed: 105 }, ability_ids: [28, 39], hidden_ability_id: 98 }] },
  { id: 65, identifier: "alakazam", name: { ja: "フーディン", en: "Alakazam" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0065-default", identifier: "alakazam", name: { ja: "フーディン", en: "Alakazam" }, form_type: "default", types: ["psychic"], stats: { hp: 55, attack: 50, defense: 45, sp_attack: 135, sp_defense: 95, speed: 120 }, ability_ids: [28, 39], hidden_ability_id: 98 }, { form_id: "0065-mega", identifier: "alakazam-mega", name: { ja: "メガフーディン", en: "Mega Alakazam" }, form_type: "mega", types: ["psychic"], stats: { hp: 55, attack: 50, defense: 65, sp_attack: 175, sp_defense: 105, speed: 150 }, ability_ids: [140] }] },
  { id: 66, identifier: "machop", name: { ja: "ワンリキー", en: "Machop" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0066-default", identifier: "machop", name: { ja: "ワンリキー", en: "Machop" }, form_type: "default", types: ["fighting"], stats: { hp: 70, attack: 80, defense: 50, sp_attack: 35, sp_defense: 35, speed: 35 }, ability_ids: [62, 99], hidden_ability_id: 80 }] },
  { id: 67, identifier: "machoke", name: { ja: "ゴーリキー", en: "Machoke" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0067-default", identifier: "machoke", name: { ja: "ゴーリキー", en: "Machoke" }, form_type: "default", types: ["fighting"], stats: { hp: 80, attack: 100, defense: 70, sp_attack: 50, sp_defense: 60, speed: 45 }, ability_ids: [62, 99], hidden_ability_id: 80 }] },
  { id: 68, identifier: "machamp", name: { ja: "カイリキー", en: "Machamp" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0068-default", identifier: "machamp", name: { ja: "カイリキー", en: "Machamp" }, form_type: "default", types: ["fighting"], stats: { hp: 90, attack: 130, defense: 80, sp_attack: 65, sp_defense: 85, speed: 55 }, ability_ids: [62, 99], hidden_ability_id: 80 }] },
  { id: 69, identifier: "bellsprout", name: { ja: "マダツボミ", en: "Bellsprout" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0069-default", identifier: "bellsprout", name: { ja: "マダツボミ", en: "Bellsprout" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 50, attack: 75, defense: 35, sp_attack: 70, sp_defense: 30, speed: 40 }, ability_ids: [34], hidden_ability_id: 82 }] },
  { id: 70, identifier: "weepinbell", name: { ja: "ウツドン", en: "Weepinbell" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0070-default", identifier: "weepinbell", name: { ja: "ウツドン", en: "Weepinbell" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 65, attack: 90, defense: 50, sp_attack: 85, sp_defense: 45, speed: 55 }, ability_ids: [34], hidden_ability_id: 82 }] },
  { id: 71, identifier: "victreebel", name: { ja: "ウツボット", en: "Victreebel" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0071-default", identifier: "victreebel", name: { ja: "ウツボット", en: "Victreebel" }, form_type: "default", types: ["grass", "poison"], stats: { hp: 80, attack: 105, defense: 65, sp_attack: 100, sp_defense: 70, speed: 70 }, ability_ids: [34], hidden_ability_id: 82 }] },
  { id: 72, identifier: "tentacool", name: { ja: "メノクラゲ", en: "Tentacool" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0072-default", identifier: "tentacool", name: { ja: "メノクラゲ", en: "Tentacool" }, form_type: "default", types: ["water", "poison"], stats: { hp: 40, attack: 40, defense: 35, sp_attack: 50, sp_defense: 100, speed: 70 }, ability_ids: [29, 64], hidden_ability_id: 44 }] },
  { id: 73, identifier: "tentacruel", name: { ja: "ドククラゲ", en: "Tentacruel" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0073-default", identifier: "tentacruel", name: { ja: "ドククラゲ", en: "Tentacruel" }, form_type: "default", types: ["water", "poison"], stats: { hp: 80, attack: 70, defense: 65, sp_attack: 80, sp_defense: 120, speed: 100 }, ability_ids: [29, 64], hidden_ability_id: 44 }] },
  { id: 74, identifier: "geodude", name: { ja: "イシツブテ", en: "Geodude" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0074-default", identifier: "geodude", name: { ja: "イシツブテ", en: "Geodude" }, form_type: "default", types: ["rock", "ground"], stats: { hp: 40, attack: 80, defense: 100, sp_attack: 30, sp_defense: 30, speed: 20 }, ability_ids: [69, 5], hidden_ability_id: 8 }] },
  { id: 75, identifier: "graveler", name: { ja: "ゴローン", en: "Graveler" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0075-default", identifier: "graveler", name: { ja: "ゴローン", en: "Graveler" }, form_type: "default", types: ["rock", "ground"], stats: { hp: 55, attack: 95, defense: 115, sp_attack: 45, sp_defense: 45, speed: 35 }, ability_ids: [69, 5], hidden_ability_id: 8 }] },
  { id: 76, identifier: "golem", name: { ja: "ゴローニャ", en: "Golem" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0076-default", identifier: "golem", name: { ja: "ゴローニャ", en: "Golem" }, form_type: "default", types: ["rock", "ground"], stats: { hp: 80, attack: 120, defense: 130, sp_attack: 55, sp_defense: 65, speed: 45 }, ability_ids: [69, 5], hidden_ability_id: 8 }] },
  { id: 77, identifier: "ponyta", name: { ja: "ポニータ", en: "Ponyta" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0077-default", identifier: "ponyta", name: { ja: "ポニータ", en: "Ponyta" }, form_type: "default", types: ["fire"], stats: { hp: 50, attack: 85, defense: 55, sp_attack: 65, sp_defense: 65, speed: 90 }, ability_ids: [50, 18], hidden_ability_id: 49 }] },
  { id: 78, identifier: "rapidash", name: { ja: "ギャロップ", en: "Rapidash" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0078-default", identifier: "rapidash", name: { ja: "ギャロップ", en: "Rapidash" }, form_type: "default", types: ["fire"], stats: { hp: 65, attack: 100, defense: 70, sp_attack: 80, sp_defense: 80, speed: 105 }, ability_ids: [50, 18], hidden_ability_id: 49 }] },
  { id: 79, identifier: "slowpoke", name: { ja: "ヤドン", en: "Slowpoke" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0079-default", identifier: "slowpoke", name: { ja: "ヤドン", en: "Slowpoke" }, form_type: "default", types: ["water", "psychic"], stats: { hp: 90, attack: 65, defense: 65, sp_attack: 40, sp_defense: 40, speed: 15 }, ability_ids: [12, 20], hidden_ability_id: 144 }] },
  { id: 80, identifier: "slowbro", name: { ja: "ヤドラン", en: "Slowbro" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0080-default", identifier: "slowbro", name: { ja: "ヤドラン", en: "Slowbro" }, form_type: "default", types: ["water", "psychic"], stats: { hp: 95, attack: 75, defense: 110, sp_attack: 100, sp_defense: 80, speed: 30 }, ability_ids: [12, 20], hidden_ability_id: 144 }, { form_id: "0080-mega", identifier: "slowbro-mega", name: { ja: "メガヤドラン", en: "Mega Slowbro" }, form_type: "mega", types: ["water", "psychic"], stats: { hp: 95, attack: 75, defense: 180, sp_attack: 130, sp_defense: 80, speed: 30 }, ability_ids: [75] }] },
  { id: 81, identifier: "magnemite", name: { ja: "コイル", en: "Magnemite" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0081-default", identifier: "magnemite", name: { ja: "コイル", en: "Magnemite" }, form_type: "default", types: ["electric", "steel"], stats: { hp: 25, attack: 35, defense: 70, sp_attack: 95, sp_defense: 55, speed: 45 }, ability_ids: [42, 5], hidden_ability_id: 148 }] },
  { id: 82, identifier: "magneton", name: { ja: "レアコイル", en: "Magneton" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0082-default", identifier: "magneton", name: { ja: "レアコイル", en: "Magneton" }, form_type: "default", types: ["electric", "steel"], stats: { hp: 50, attack: 60, defense: 95, sp_attack: 120, sp_defense: 70, speed: 70 }, ability_ids: [42, 5], hidden_ability_id: 148 }] },
  { id: 83, identifier: "farfetchd", name: { ja: "カモネギ", en: "Farfetch'd" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0083-default", identifier: "farfetchd", name: { ja: "カモネギ", en: "Farfetch'd" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 52, attack: 90, defense: 55, sp_attack: 58, sp_defense: 62, speed: 60 }, ability_ids: [51, 39], hidden_ability_id: 128 }] },
  { id: 84, identifier: "doduo", name: { ja: "ドードー", en: "Doduo" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0084-default", identifier: "doduo", name: { ja: "ドードー", en: "Doduo" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 35, attack: 85, defense: 45, sp_attack: 35, sp_defense: 35, speed: 75 }, ability_ids: [50, 48], hidden_ability_id: 77 }] },
  { id: 85, identifier: "dodrio", name: { ja: "ドードリオ", en: "Dodrio" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0085-default", identifier: "dodrio", name: { ja: "ドードリオ", en: "Dodrio" }, form_type: "default", types: ["normal", "flying"], stats: { hp: 60, attack: 110, defense: 70, sp_attack: 60, sp_defense: 60, speed: 110 }, ability_ids: [50, 48], hidden_ability_id: 77 }] },
  { id: 86, identifier: "seel", name: { ja: "パウワウ", en: "Seel" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0086-default", identifier: "seel", name: { ja: "パウワウ", en: "Seel" }, form_type: "default", types: ["water"], stats: { hp: 65, attack: 45, defense: 55, sp_attack: 45, sp_defense: 70, speed: 45 }, ability_ids: [47, 93], hidden_ability_id: 115 }] },
  { id: 87, identifier: "dewgong", name: { ja: "ジュゴン", en: "Dewgong" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0087-default", identifier: "dewgong", name: { ja: "ジュゴン", en: "Dewgong" }, form_type: "default", types: ["water", "ice"], stats: { hp: 90, attack: 70, defense: 80, sp_attack: 70, sp_defense: 95, speed: 70 }, ability_ids: [47, 93], hidden_ability_id: 115 }] },
  { id: 88, identifier: "grimer", name: { ja: "ベトベター", en: "Grimer" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0088-default", identifier: "grimer", name: { ja: "ベトベター", en: "Grimer" }, form_type: "default", types: ["poison"], stats: { hp: 80, attack: 80, defense: 50, sp_attack: 40, sp_defense: 50, speed: 25 }, ability_ids: [1, 60], hidden_ability_id: 143 }] },
  { id: 89, identifier: "muk", name: { ja: "ベトベトン", en: "Muk" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0089-default", identifier: "muk", name: { ja: "ベトベトン", en: "Muk" }, form_type: "default", types: ["poison"], stats: { hp: 105, attack: 105, defense: 75, sp_attack: 65, sp_defense: 100, speed: 50 }, ability_ids: [1, 60], hidden_ability_id: 143 }] },
  { id: 90, identifier: "shellder", name: { ja: "シェルダー", en: "Shellder" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0090-default", identifier: "shellder", name: { ja: "シェルダー", en: "Shellder" }, form_type: "default", types: ["water"], stats: { hp: 30, attack: 65, defense: 100, sp_attack: 45, sp_defense: 25, speed: 40 }, ability_ids: [75, 92], hidden_ability_id: 142 }] },
  { id: 91, identifier: "cloyster", name: { ja: "パルシェン", en: "Cloyster" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0091-default", identifier: "cloyster", name: { ja: "パルシェン", en: "Cloyster" }, form_type: "default", types: ["water", "ice"], stats: { hp: 50, attack: 95, defense: 180, sp_attack: 85, sp_defense: 45, speed: 70 }, ability_ids: [75, 92], hidden_ability_id: 142 }] },
  { id: 92, identifier: "gastly", name: { ja: "ゴース", en: "Gastly" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0092-default", identifier: "gastly", name: { ja: "ゴース", en: "Gastly" }, form_type: "default", types: ["ghost", "poison"], stats: { hp: 30, attack: 35, defense: 30, sp_attack: 100, sp_defense: 35, speed: 80 }, ability_ids: [26] }] },
  { id: 93, identifier: "haunter", name: { ja: "ゴースト", en: "Haunter" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0093-default", identifier: "haunter", name: { ja: "ゴースト", en: "Haunter" }, form_type: "default", types: ["ghost", "poison"], stats: { hp: 45, attack: 50, defense: 45, sp_attack: 115, sp_defense: 55, speed: 95 }, ability_ids: [26] }] },
  { id: 94, identifier: "gengar", name: { ja: "ゲンガー", en: "Gengar" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0094-default", identifier: "gengar", name: { ja: "ゲンガー", en: "Gengar" }, form_type: "default", types: ["ghost", "poison"], stats: { hp: 60, attack: 65, defense: 60, sp_attack: 130, sp_defense: 75, speed: 110 }, ability_ids: [130] }, { form_id: "0094-mega", identifier: "gengar-mega", name: { ja: "メガゲンガー", en: "Mega Gengar" }, form_type: "mega", types: ["ghost", "poison"], stats: { hp: 60, attack: 65, defense: 80, sp_attack: 170, sp_defense: 95, speed: 130 }, ability_ids: [23] }] },
  { id: 95, identifier: "onix", name: { ja: "イワーク", en: "Onix" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0095-default", identifier: "onix", name: { ja: "イワーク", en: "Onix" }, form_type: "default", types: ["rock", "ground"], stats: { hp: 35, attack: 45, defense: 160, sp_attack: 30, sp_defense: 45, speed: 70 }, ability_ids: [69, 5], hidden_ability_id: 133 }] },
  { id: 96, identifier: "drowzee", name: { ja: "スリープ", en: "Drowzee" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0096-default", identifier: "drowzee", name: { ja: "スリープ", en: "Drowzee" }, form_type: "default", types: ["psychic"], stats: { hp: 60, attack: 48, defense: 45, sp_attack: 43, sp_defense: 90, speed: 42 }, ability_ids: [15, 108], hidden_ability_id: 39 }] },
  { id: 97, identifier: "hypno", name: { ja: "スリーパー", en: "Hypno" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0097-default", identifier: "hypno", name: { ja: "スリーパー", en: "Hypno" }, form_type: "default", types: ["psychic"], stats: { hp: 85, attack: 73, defense: 70, sp_attack: 73, sp_defense: 115, speed: 67 }, ability_ids: [15, 108], hidden_ability_id: 39 }] },
  { id: 98, identifier: "krabby", name: { ja: "クラブ", en: "Krabby" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0098-default", identifier: "krabby", name: { ja: "クラブ", en: "Krabby" }, form_type: "default", types: ["water"], stats: { hp: 30, attack: 105, defense: 90, sp_attack: 25, sp_defense: 25, speed: 50 }, ability_ids: [52, 75], hidden_ability_id: 125 }] },
  { id: 99, identifier: "kingler", name: { ja: "キングラー", en: "Kingler" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0099-default", identifier: "kingler", name: { ja: "キングラー", en: "Kingler" }, form_type: "default", types: ["water"], stats: { hp: 55, attack: 130, defense: 115, sp_attack: 50, sp_defense: 50, speed: 75 }, ability_ids: [52, 75], hidden_ability_id: 125 }] },
  { id: 100, identifier: "voltorb", name: { ja: "ビリリダマ", en: "Voltorb" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0100-default", identifier: "voltorb", name: { ja: "ビリリダマ", en: "Voltorb" }, form_type: "default", types: ["electric"], stats: { hp: 40, attack: 30, defense: 50, sp_attack: 55, sp_defense: 55, speed: 100 }, ability_ids: [43, 9], hidden_ability_id: 106 }] },
  { id: 101, identifier: "electrode", name: { ja: "マルマイン", en: "Electrode" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0101-default", identifier: "electrode", name: { ja: "マルマイン", en: "Electrode" }, form_type: "default", types: ["electric"], stats: { hp: 60, attack: 50, defense: 70, sp_attack: 80, sp_defense: 80, speed: 150 }, ability_ids: [43, 9], hidden_ability_id: 106 }] },
  { id: 102, identifier: "exeggcute", name: { ja: "タマタマ", en: "Exeggcute" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0102-default", identifier: "exeggcute", name: { ja: "タマタマ", en: "Exeggcute" }, form_type: "default", types: ["grass", "psychic"], stats: { hp: 60, attack: 40, defense: 80, sp_attack: 60, sp_defense: 45, speed: 40 }, ability_ids: [34], hidden_ability_id: 139 }] },
  { id: 103, identifier: "exeggutor", name: { ja: "ナッシー", en: "Exeggutor" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0103-default", identifier: "exeggutor", name: { ja: "ナッシー", en: "Exeggutor" }, form_type: "default", types: ["grass", "psychic"], stats: { hp: 95, attack: 95, defense: 85, sp_attack: 125, sp_defense: 75, speed: 55 }, ability_ids: [34], hidden_ability_id: 139 }] },
  { id: 104, identifier: "cubone", name: { ja: "カラカラ", en: "Cubone" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0104-default", identifier: "cubone", name: { ja: "カラカラ", en: "Cubone" }, form_type: "default", types: ["ground"], stats: { hp: 50, attack: 50, defense: 95, sp_attack: 40, sp_defense: 50, speed: 35 }, ability_ids: [69, 31], hidden_ability_id: 4 }] },
  { id: 105, identifier: "marowak", name: { ja: "ガラガラ", en: "Marowak" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0105-default", identifier: "marowak", name: { ja: "ガラガラ", en: "Marowak" }, form_type: "default", types: ["ground"], stats: { hp: 60, attack: 80, defense: 110, sp_attack: 50, sp_defense: 80, speed: 45 }, ability_ids: [69, 31], hidden_ability_id: 4 }] },
  { id: 106, identifier: "hitmonlee", name: { ja: "サワムラー", en: "Hitmonlee" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0106-default", identifier: "hitmonlee", name: { ja: "サワムラー", en: "Hitmonlee" }, form_type: "default", types: ["fighting"], stats: { hp: 50, attack: 120, defense: 53, sp_attack: 35, sp_defense: 110, speed: 87 }, ability_ids: [7, 120], hidden_ability_id: 84 }] },
  { id: 107, identifier: "hitmonchan", name: { ja: "エビワラー", en: "Hitmonchan" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0107-default", identifier: "hitmonchan", name: { ja: "エビワラー", en: "Hitmonchan" }, form_type: "default", types: ["fighting"], stats: { hp: 50, attack: 105, defense: 79, sp_attack: 35, sp_defense: 110, speed: 76 }, ability_ids: [51, 89], hidden_ability_id: 39 }] },
  { id: 108, identifier: "lickitung", name: { ja: "ベロリンガ", en: "Lickitung" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0108-default", identifier: "lickitung", name: { ja: "ベロリンガ", en: "Lickitung" }, form_type: "default", types: ["normal"], stats: { hp: 90, attack: 55, defense: 75, sp_attack: 60, sp_defense: 75, speed: 30 }, ability_ids: [20, 12], hidden_ability_id: 13 }] },
  { id: 109, identifier: "koffing", name: { ja: "ドガース", en: "Koffing" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0109-default", identifier: "koffing", name: { ja: "ドガース", en: "Koffing" }, form_type: "default", types: ["poison"], stats: { hp: 40, attack: 65, defense: 95, sp_attack: 60, sp_defense: 45, speed: 35 }, ability_ids: [26, 256], hidden_ability_id: 1 }] },
  { id: 110, identifier: "weezing", name: { ja: "マタドガス", en: "Weezing" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0110-default", identifier: "weezing", name: { ja: "マタドガス", en: "Weezing" }, form_type: "default", types: ["poison"], stats: { hp: 65, attack: 90, defense: 120, sp_attack: 85, sp_defense: 70, speed: 60 }, ability_ids: [26, 256], hidden_ability_id: 1 }] },
  { id: 111, identifier: "rhyhorn", name: { ja: "サイホーン", en: "Rhyhorn" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0111-default", identifier: "rhyhorn", name: { ja: "サイホーン", en: "Rhyhorn" }, form_type: "default", types: ["ground", "rock"], stats: { hp: 80, attack: 85, defense: 95, sp_attack: 30, sp_defense: 30, speed: 25 }, ability_ids: [31, 69], hidden_ability_id: 120 }] },
  { id: 112, identifier: "rhydon", name: { ja: "サイドン", en: "Rhydon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0112-default", identifier: "rhydon", name: { ja: "サイドン", en: "Rhydon" }, form_type: "default", types: ["ground", "rock"], stats: { hp: 105, attack: 130, defense: 120, sp_attack: 45, sp_defense: 45, speed: 40 }, ability_ids: [31, 69], hidden_ability_id: 120 }] },
  { id: 113, identifier: "chansey", name: { ja: "ラッキー", en: "Chansey" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0113-default", identifier: "chansey", name: { ja: "ラッキー", en: "Chansey" }, form_type: "default", types: ["normal"], stats: { hp: 250, attack: 5, defense: 5, sp_attack: 35, sp_defense: 105, speed: 50 }, ability_ids: [30, 32], hidden_ability_id: 131 }] },
  { id: 114, identifier: "tangela", name: { ja: "モンジャラ", en: "Tangela" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0114-default", identifier: "tangela", name: { ja: "モンジャラ", en: "Tangela" }, form_type: "default", types: ["grass"], stats: { hp: 65, attack: 55, defense: 115, sp_attack: 100, sp_defense: 40, speed: 60 }, ability_ids: [34, 102], hidden_ability_id: 144 }] },
  { id: 115, identifier: "kangaskhan", name: { ja: "ガルーラ", en: "Kangaskhan" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0115-default", identifier: "kangaskhan", name: { ja: "ガルーラ", en: "Kangaskhan" }, form_type: "default", types: ["normal"], stats: { hp: 105, attack: 95, defense: 80, sp_attack: 40, sp_defense: 80, speed: 90 }, ability_ids: [48, 113], hidden_ability_id: 39 }, { form_id: "0115-mega", identifier: "kangaskhan-mega", name: { ja: "メガガルーラ", en: "Mega Kangaskhan" }, form_type: "mega", types: ["normal"], stats: { hp: 105, attack: 125, defense: 100, sp_attack: 60, sp_defense: 100, speed: 100 }, ability_ids: [184] }] },
  { id: 116, identifier: "horsea", name: { ja: "タッツー", en: "Horsea" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0116-default", identifier: "horsea", name: { ja: "タッツー", en: "Horsea" }, form_type: "default", types: ["water"], stats: { hp: 30, attack: 40, defense: 70, sp_attack: 70, sp_defense: 25, speed: 60 }, ability_ids: [33, 97], hidden_ability_id: 6 }] },
  { id: 117, identifier: "seadra", name: { ja: "シードラ", en: "Seadra" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0117-default", identifier: "seadra", name: { ja: "シードラ", en: "Seadra" }, form_type: "default", types: ["water"], stats: { hp: 55, attack: 65, defense: 95, sp_attack: 95, sp_defense: 45, speed: 85 }, ability_ids: [38, 97], hidden_ability_id: 6 }] },
  { id: 118, identifier: "goldeen", name: { ja: "トサキント", en: "Goldeen" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0118-default", identifier: "goldeen", name: { ja: "トサキント", en: "Goldeen" }, form_type: "default", types: ["water"], stats: { hp: 45, attack: 67, defense: 60, sp_attack: 35, sp_defense: 50, speed: 63 }, ability_ids: [33, 41], hidden_ability_id: 31 }] },
  { id: 119, identifier: "seaking", name: { ja: "アズマオウ", en: "Seaking" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0119-default", identifier: "seaking", name: { ja: "アズマオウ", en: "Seaking" }, form_type: "default", types: ["water"], stats: { hp: 80, attack: 92, defense: 65, sp_attack: 65, sp_defense: 80, speed: 68 }, ability_ids: [33, 41], hidden_ability_id: 31 }] },
  { id: 120, identifier: "staryu", name: { ja: "ヒトデマン", en: "Staryu" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0120-default", identifier: "staryu", name: { ja: "ヒトデマン", en: "Staryu" }, form_type: "default", types: ["water"], stats: { hp: 30, attack: 45, defense: 55, sp_attack: 70, sp_defense: 55, speed: 85 }, ability_ids: [35, 30], hidden_ability_id: 148 }] },
  { id: 121, identifier: "starmie", name: { ja: "スターミー", en: "Starmie" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0121-default", identifier: "starmie", name: { ja: "スターミー", en: "Starmie" }, form_type: "default", types: ["water", "psychic"], stats: { hp: 60, attack: 75, defense: 85, sp_attack: 100, sp_defense: 85, speed: 115 }, ability_ids: [35, 30], hidden_ability_id: 148 }] },
  { id: 122, identifier: "mr-mime", name: { ja: "バリヤード", en: "Mr. Mime" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0122-default", identifier: "mr-mime", name: { ja: "バリヤード", en: "Mr. Mime" }, form_type: "default", types: ["psychic", "fairy"], stats: { hp: 40, attack: 45, defense: 65, sp_attack: 100, sp_defense: 120, speed: 90 }, ability_ids: [43, 111], hidden_ability_id: 101 }] },
  { id: 123, identifier: "scyther", name: { ja: "ストライク", en: "Scyther" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0123-default", identifier: "scyther", name: { ja: "ストライク", en: "Scyther" }, form_type: "default", types: ["bug", "flying"], stats: { hp: 70, attack: 110, defense: 80, sp_attack: 55, sp_defense: 80, speed: 105 }, ability_ids: [68, 101], hidden_ability_id: 80 }] },
  { id: 124, identifier: "jynx", name: { ja: "ルージュラ", en: "Jynx" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0124-default", identifier: "jynx", name: { ja: "ルージュラ", en: "Jynx" }, form_type: "default", types: ["ice", "psychic"], stats: { hp: 65, attack: 50, defense: 35, sp_attack: 115, sp_defense: 95, speed: 95 }, ability_ids: [12, 108], hidden_ability_id: 87 }] },
  { id: 125, identifier: "electabuzz", name: { ja: "エレブー", en: "Electabuzz" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0125-default", identifier: "electabuzz", name: { ja: "エレブー", en: "Electabuzz" }, form_type: "default", types: ["electric"], stats: { hp: 65, attack: 83, defense: 57, sp_attack: 95, sp_defense: 85, speed: 105 }, ability_ids: [9], hidden_ability_id: 72 }] },
  { id: 126, identifier: "magmar", name: { ja: "ブーバー", en: "Magmar" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0126-default", identifier: "magmar", name: { ja: "ブーバー", en: "Magmar" }, form_type: "default", types: ["fire"], stats: { hp: 65, attack: 95, defense: 57, sp_attack: 100, sp_defense: 85, speed: 93 }, ability_ids: [49], hidden_ability_id: 72 }] },
  { id: 127, identifier: "pinsir", name: { ja: "カイロス", en: "Pinsir" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0127-default", identifier: "pinsir", name: { ja: "カイロス", en: "Pinsir" }, form_type: "default", types: ["bug"], stats: { hp: 65, attack: 125, defense: 100, sp_attack: 55, sp_defense: 70, speed: 85 }, ability_ids: [52, 104], hidden_ability_id: 153 }, { form_id: "0127-mega", identifier: "pinsir-mega", name: { ja: "メガカイロス", en: "Mega Pinsir" }, form_type: "mega", types: ["bug", "flying"], stats: { hp: 65, attack: 155, defense: 120, sp_attack: 65, sp_defense: 90, speed: 105 }, ability_ids: [177] }] },
  { id: 128, identifier: "tauros", name: { ja: "ケンタロス", en: "Tauros" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0128-default", identifier: "tauros", name: { ja: "ケンタロス", en: "Tauros" }, form_type: "default", types: ["normal"], stats: { hp: 75, attack: 100, defense: 95, sp_attack: 40, sp_defense: 70, speed: 110 }, ability_ids: [22, 83], hidden_ability_id: 125 }] },
  { id: 129, identifier: "magikarp", name: { ja: "コイキング", en: "Magikarp" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0129-default", identifier: "magikarp", name: { ja: "コイキング", en: "Magikarp" }, form_type: "default", types: ["water"], stats: { hp: 20, attack: 10, defense: 55, sp_attack: 15, sp_defense: 20, speed: 80 }, ability_ids: [33], hidden_ability_id: 155 }] },
  { id: 130, identifier: "gyarados", name: { ja: "ギャラドス", en: "Gyarados" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0130-default", identifier: "gyarados", name: { ja: "ギャラドス", en: "Gyarados" }, form_type: "default", types: ["water", "flying"], stats: { hp: 95, attack: 125, defense: 79, sp_attack: 60, sp_defense: 100, speed: 81 }, ability_ids: [22], hidden_ability_id: 153 }, { form_id: "0130-mega", identifier: "gyarados-mega", name: { ja: "メガギャラドス", en: "Mega Gyarados" }, form_type: "mega", types: ["water", "dark"], stats: { hp: 95, attack: 155, defense: 109, sp_attack: 70, sp_defense: 130, speed: 81 }, ability_ids: [104] }] },
  { id: 131, identifier: "lapras", name: { ja: "ラプラス", en: "Lapras" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0131-default", identifier: "lapras", name: { ja: "ラプラス", en: "Lapras" }, form_type: "default", types: ["water", "ice"], stats: { hp: 130, attack: 85, defense: 80, sp_attack: 85, sp_defense: 95, speed: 60 }, ability_ids: [11, 75], hidden_ability_id: 93 }] },
  { id: 132, identifier: "ditto", name: { ja: "メタモン", en: "Ditto" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0132-default", identifier: "ditto", name: { ja: "メタモン", en: "Ditto" }, form_type: "default", types: ["normal"], stats: { hp: 48, attack: 48, defense: 48, sp_attack: 48, sp_defense: 48, speed: 48 }, ability_ids: [7], hidden_ability_id: 150 }] },
  { id: 133, identifier: "eevee", name: { ja: "イーブイ", en: "Eevee" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0133-default", identifier: "eevee", name: { ja: "イーブイ", en: "Eevee" }, form_type: "default", types: ["normal"], stats: { hp: 55, attack: 55, defense: 50, sp_attack: 45, sp_defense: 65, speed: 55 }, ability_ids: [50, 91], hidden_ability_id: 107 }] },
  { id: 134, identifier: "vaporeon", name: { ja: "シャワーズ", en: "Vaporeon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0134-default", identifier: "vaporeon", name: { ja: "シャワーズ", en: "Vaporeon" }, form_type: "default", types: ["water"], stats: { hp: 130, attack: 65, defense: 60, sp_attack: 110, sp_defense: 95, speed: 65 }, ability_ids: [11], hidden_ability_id: 93 }] },
  { id: 135, identifier: "jolteon", name: { ja: "サンダース", en: "Jolteon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0135-default", identifier: "jolteon", name: { ja: "サンダース", en: "Jolteon" }, form_type: "default", types: ["electric"], stats: { hp: 65, attack: 65, defense: 60, sp_attack: 110, sp_defense: 95, speed: 130 }, ability_ids: [10], hidden_ability_id: 95 }] },
  { id: 136, identifier: "flareon", name: { ja: "ブースター", en: "Flareon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0136-default", identifier: "flareon", name: { ja: "ブースター", en: "Flareon" }, form_type: "default", types: ["fire"], stats: { hp: 65, attack: 130, defense: 60, sp_attack: 95, sp_defense: 110, speed: 65 }, ability_ids: [18], hidden_ability_id: 62 }] },
  { id: 137, identifier: "porygon", name: { ja: "ポリゴン", en: "Porygon" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0137-default", identifier: "porygon", name: { ja: "ポリゴン", en: "Porygon" }, form_type: "default", types: ["normal"], stats: { hp: 65, attack: 60, defense: 70, sp_attack: 85, sp_defense: 75, speed: 40 }, ability_ids: [36, 88], hidden_ability_id: 148 }] },
  { id: 138, identifier: "omanyte", name: { ja: "オムナイト", en: "Omanyte" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0138-default", identifier: "omanyte", name: { ja: "オムナイト", en: "Omanyte" }, form_type: "default", types: ["rock", "water"], stats: { hp: 35, attack: 40, defense: 100, sp_attack: 90, sp_defense: 55, speed: 35 }, ability_ids: [33, 75], hidden_ability_id: 133 }] },
  { id: 139, identifier: "omastar", name: { ja: "オムスター", en: "Omastar" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0139-default", identifier: "omastar", name: { ja: "オムスター", en: "Omastar" }, form_type: "default", types: ["rock", "water"], stats: { hp: 70, attack: 60, defense: 125, sp_attack: 115, sp_defense: 70, speed: 55 }, ability_ids: [33, 75], hidden_ability_id: 133 }] },
  { id: 140, identifier: "kabuto", name: { ja: "カブト", en: "Kabuto" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0140-default", identifier: "kabuto", name: { ja: "カブト", en: "Kabuto" }, form_type: "default", types: ["rock", "water"], stats: { hp: 30, attack: 80, defense: 90, sp_attack: 55, sp_defense: 45, speed: 55 }, ability_ids: [33, 4], hidden_ability_id: 133 }] },
  { id: 141, identifier: "kabutops", name: { ja: "カブトプス", en: "Kabutops" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0141-default", identifier: "kabutops", name: { ja: "カブトプス", en: "Kabutops" }, form_type: "default", types: ["rock", "water"], stats: { hp: 60, attack: 115, defense: 105, sp_attack: 65, sp_defense: 70, speed: 80 }, ability_ids: [33, 4], hidden_ability_id: 133 }] },
  { id: 142, identifier: "aerodactyl", name: { ja: "プテラ", en: "Aerodactyl" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0142-default", identifier: "aerodactyl", name: { ja: "プテラ", en: "Aerodactyl" }, form_type: "default", types: ["rock", "flying"], stats: { hp: 80, attack: 105, defense: 65, sp_attack: 60, sp_defense: 75, speed: 130 }, ability_ids: [69, 46], hidden_ability_id: 127 }, { form_id: "0142-mega", identifier: "aerodactyl-mega", name: { ja: "メガプテラ", en: "Mega Aerodactyl" }, form_type: "mega", types: ["rock", "flying"], stats: { hp: 80, attack: 135, defense: 85, sp_attack: 70, sp_defense: 95, speed: 150 }, ability_ids: [153] }] },
  { id: 143, identifier: "snorlax", name: { ja: "カビゴン", en: "Snorlax" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0143-default", identifier: "snorlax", name: { ja: "カビゴン", en: "Snorlax" }, form_type: "default", types: ["normal"], stats: { hp: 160, attack: 110, defense: 65, sp_attack: 65, sp_defense: 110, speed: 30 }, ability_ids: [17, 47], hidden_ability_id: 82 }] },
  { id: 144, identifier: "articuno", name: { ja: "フリーザー", en: "Articuno" }, is_legendary: true, is_mythical: false, forms: [{ form_id: "0144-default", identifier: "articuno", name: { ja: "フリーザー", en: "Articuno" }, form_type: "default", types: ["ice", "flying"], stats: { hp: 90, attack: 85, defense: 100, sp_attack: 95, sp_defense: 125, speed: 85 }, ability_ids: [46], hidden_ability_id: 81 }] },
  { id: 145, identifier: "zapdos", name: { ja: "サンダー", en: "Zapdos" }, is_legendary: true, is_mythical: false, forms: [{ form_id: "0145-default", identifier: "zapdos", name: { ja: "サンダー", en: "Zapdos" }, form_type: "default", types: ["electric", "flying"], stats: { hp: 90, attack: 90, defense: 85, sp_attack: 125, sp_defense: 90, speed: 100 }, ability_ids: [46], hidden_ability_id: 9 }] },
  { id: 146, identifier: "moltres", name: { ja: "ファイヤー", en: "Moltres" }, is_legendary: true, is_mythical: false, forms: [{ form_id: "0146-default", identifier: "moltres", name: { ja: "ファイヤー", en: "Moltres" }, form_type: "default", types: ["fire", "flying"], stats: { hp: 90, attack: 100, defense: 90, sp_attack: 125, sp_defense: 85, speed: 90 }, ability_ids: [46], hidden_ability_id: 49 }] },
  { id: 147, identifier: "dratini", name: { ja: "ミニリュウ", en: "Dratini" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0147-default", identifier: "dratini", name: { ja: "ミニリュウ", en: "Dratini" }, form_type: "default", types: ["dragon"], stats: { hp: 41, attack: 64, defense: 45, sp_attack: 50, sp_defense: 50, speed: 50 }, ability_ids: [61], hidden_ability_id: 63 }] },
  { id: 148, identifier: "dragonair", name: { ja: "ハクリュー", en: "Dragonair" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0148-default", identifier: "dragonair", name: { ja: "ハクリュー", en: "Dragonair" }, form_type: "default", types: ["dragon"], stats: { hp: 61, attack: 84, defense: 65, sp_attack: 70, sp_defense: 70, speed: 70 }, ability_ids: [61], hidden_ability_id: 63 }] },
  { id: 149, identifier: "dragonite", name: { ja: "カイリュー", en: "Dragonite" }, is_legendary: false, is_mythical: false, forms: [{ form_id: "0149-default", identifier: "dragonite", name: { ja: "カイリュー", en: "Dragonite" }, form_type: "default", types: ["dragon", "flying"], stats: { hp: 91, attack: 134, defense: 95, sp_attack: 100, sp_defense: 100, speed: 80 }, ability_ids: [39], hidden_ability_id: 136 }] },
  { id: 150, identifier: "mewtwo", name: { ja: "ミュウツー", en: "Mewtwo" }, is_legendary: true, is_mythical: false, forms: [{ form_id: "0150-default", identifier: "mewtwo", name: { ja: "ミュウツー", en: "Mewtwo" }, form_type: "default", types: ["psychic"], stats: { hp: 106, attack: 110, defense: 90, sp_attack: 154, sp_defense: 90, speed: 130 }, ability_ids: [46], hidden_ability_id: 127 }, { form_id: "0150-mega-x", identifier: "mewtwo-mega-x", name: { ja: "メガミュウツーX", en: "Mega Mewtwo X" }, form_type: "mega", types: ["psychic", "fighting"], stats: { hp: 106, attack: 190, defense: 100, sp_attack: 154, sp_defense: 100, speed: 130 }, ability_ids: [80] }, { form_id: "0150-mega-y", identifier: "mewtwo-mega-y", name: { ja: "メガミュウツーY", en: "Mega Mewtwo Y" }, form_type: "mega", types: ["psychic"], stats: { hp: 106, attack: 150, defense: 70, sp_attack: 194, sp_defense: 120, speed: 140 }, ability_ids: [15] }] },
  { id: 151, identifier: "mew", name: { ja: "ミュウ", en: "Mew" }, is_legendary: false, is_mythical: true, forms: [{ form_id: "0151-default", identifier: "mew", name: { ja: "ミュウ", en: "Mew" }, form_type: "default", types: ["psychic"], stats: { hp: 100, attack: 100, defense: 100, sp_attack: 100, sp_defense: 100, speed: 100 }, ability_ids: [28] }] },
];

function padId(id: number): string {
  return id.toString().padStart(4, "0");
}

async function main() {
  console.log("Generating Gen 1 Pokemon data...\n");

  await mkdir(join(DATA_DIR, "core/pokemons"), { recursive: true });
  await mkdir(join(DATA_DIR, "core/forms"), { recursive: true });

  for (const pokemon of gen1Pokemon) {
    const pokemonFile = {
      id: pokemon.id,
      identifier: pokemon.identifier,
      name: pokemon.name,
      generation: 1,
      is_legendary: pokemon.is_legendary,
      is_mythical: pokemon.is_mythical,
    };

    const formsFile = {
      pokemon_id: pokemon.id,
      forms: pokemon.forms.map((form) => ({
        form_id: form.form_id,
        identifier: form.identifier,
        name: form.name,
        form_type: form.form_type,
        is_default: form.form_type === "default",
        types: form.types,
        stats: form.stats,
        ability_ids: form.ability_ids,
        ...(form.hidden_ability_id ? { hidden_ability_id: form.hidden_ability_id } : {}),
      })),
    };

    const paddedId = padId(pokemon.id);

    await writeFile(
      join(DATA_DIR, `core/pokemons/${paddedId}.json`),
      JSON.stringify(pokemonFile, null, 2)
    );

    await writeFile(
      join(DATA_DIR, `core/forms/${paddedId}.json`),
      JSON.stringify(formsFile, null, 2)
    );

    console.log(`✓ ${paddedId} ${pokemon.name.ja} (${pokemon.name.en})`);
  }

  console.log(`\n✓ Generated ${gen1Pokemon.length} Pokemon!`);
}

main();
