name = "pokebase-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[assets]
directory = "../../data"
binding = "ASSETS"

[vars]
ALLOWED_ORIGIN = "http://localhost:3000"
IMAGES_BASE_URL = "https://images.pokebase.solclarus.me"
